# Generated by Django 4.1.5 on 2023-03-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('prov_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('icon_file', models.CharField(blank=True, max_length=20)),
                ('banner_file', models.CharField(blank=True, max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=20)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_office', models.CharField(blank=True, max_length=20)),
                ('admin_cell', models.CharField(blank=True, max_length=20)),
                ('billing_name', models.CharField(blank=True, max_length=20)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_office', models.CharField(blank=True, max_length=20)),
                ('billing_cell', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='quals',
            fields=[
                ('qual_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('qual_id', models.CharField(max_length=20)),
                ('qual_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shifts',
            fields=[
                ('shift_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_title', models.CharField(max_length=70)),
                ('shift_desc', models.CharField(max_length=200)),
                ('shift_location', models.CharField(max_length=70)),
                ('duration', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('ticketsreqd', models.CharField(max_length=120)),
                ('cont_name', models.CharField(max_length=20)),
                ('cont_email', models.EmailField(max_length=254)),
                ('cont_cell', models.CharField(max_length=20)),
                ('start_ad_date', models.DateField(blank=True, null=True)),
                ('end_ad_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(max_length=20, null=True)),
                ('used', models.CharField(max_length=20, null=True)),
                ('expired', models.CharField(max_length=20, null=True)),
                ('filled_by_us', models.CharField(blank=True, max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='base.provider')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='base.state')),
            ],
        ),
        migrations.CreateModel(
            name='prov_addresses',
            fields=[
                ('prov_add_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('prov_addy_no', models.IntegerField()),
                ('address_name', models.CharField(blank=True, max_length=50)),
                ('address_1', models.CharField(blank=True, max_length=50)),
                ('address_2', models.CharField(blank=True, max_length=50)),
                ('address_3', models.CharField(blank=True, max_length=50)),
                ('gps', models.CharField(blank=True, max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prov_addresses', to='base.provider')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
                ('topic_text1', models.CharField(blank=True, max_length=200)),
                ('topic_text2', models.CharField(blank=True, max_length=200)),
                ('topic_image', models.CharField(blank=True, max_length=400)),
                ('internal_link', models.CharField(blank=True, max_length=400)),
                ('external_link', models.CharField(blank=True, max_length=400)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('priority', models.IntegerField(null=True)),
                ('used', models.CharField(max_length=20, null=True)),
                ('filled_by_us', models.CharField(blank=True, max_length=20)),
                ('job_location', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=100)),
                ('ticketsreqd', models.CharField(max_length=100)),
                ('cont_name', models.CharField(max_length=40)),
                ('cont_email', models.EmailField(max_length=254)),
                ('cont_cell', models.CharField(max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='base.provider')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='base.region')),
            ],
        ),
        migrations.CreateModel(
            name='editor',
            fields=[
                ('editor_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
                ('topic_text1', models.CharField(blank=True, max_length=200)),
                ('topic_text2', models.CharField(blank=True, max_length=200)),
                ('topic_image', models.CharField(blank=True, max_length=400)),
                ('internal_link', models.CharField(blank=True, max_length=400)),
                ('external_link', models.CharField(blank=True, max_length=400)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('priority', models.IntegerField(null=True)),
                ('used', models.CharField(max_length=20, null=True)),
                ('filled_by_us', models.CharField(blank=True, max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='base.provider')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
                ('topic_text1', models.CharField(blank=True, max_length=200)),
                ('topic_text2', models.CharField(blank=True, max_length=200)),
                ('topic_image', models.CharField(blank=True, max_length=400)),
                ('internal_link', models.CharField(blank=True, max_length=400)),
                ('external_link', models.CharField(blank=True, max_length=400)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('priority', models.IntegerField(null=True)),
                ('used', models.CharField(max_length=20, null=True)),
                ('filled_by_us', models.CharField(blank=True, max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.provider')),
            ],
        ),
        migrations.CreateModel(
            name='adverts',
            fields=[
                ('adv_Unique_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
                ('topic_text1', models.CharField(blank=True, max_length=200)),
                ('topic_text2', models.CharField(blank=True, max_length=200)),
                ('topic_image', models.CharField(blank=True, max_length=400)),
                ('internal_link', models.CharField(blank=True, max_length=400)),
                ('external_link', models.CharField(blank=True, max_length=400)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('priority', models.IntegerField(null=True)),
                ('used', models.CharField(max_length=20, null=True)),
                ('filled_by_us', models.CharField(blank=True, max_length=20)),
                ('prov_unique_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='base.provider')),
            ],
        ),
    ]
