# Generated by Django 4.1.5 on 2023-03-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='base.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editor',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='base.region'),
            preserve_default=False,
        ),
    ]
