# Generated by Django 4.1.5 on 2023-03-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_adverts_region_courses_region_editor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='base.region'),
            preserve_default=False,
        ),
    ]
