# Generated by Django 4.1.5 on 2023-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shifts_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverts',
            name='region',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='region',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='region',
        ),
        migrations.AddField(
            model_name='adverts',
            name='topic_type',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='courses',
            name='topic_type',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='editor',
            name='topic_type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='job',
            name='topic_type',
            field=models.IntegerField(default=1),
        ),
    ]
