# Generated by Django 4.1.5 on 2023-03-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_adverts_region_remove_courses_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='base.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editor',
            name='edit_cta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='editor',
            name='edit_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='editor',
            name='edit_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='editor',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='base.region'),
            preserve_default=False,
        ),
    ]
