# Generated by Django 4.1.5 on 2023-04-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adverts_region_courses_region_editor_edit_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='adformat',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='adformat',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editor',
            name='adformat',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='adformat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
