# Generated by Django 4.1.5 on 2023-04-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_adverts_adformat_courses_adformat_editor_adformat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_groups',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='forum_topics',
            fields=[
                ('topic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(default=1)),
                ('short_name', models.CharField(max_length=50)),
                ('forum_header', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to='base.forum_groups')),
            ],
        ),
        migrations.CreateModel(
            name='forum_posts',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_head', models.CharField(max_length=50)),
                ('post_body', models.CharField(max_length=50)),
                ('post_by', models.CharField(max_length=50)),
                ('anonymous', models.BooleanField(default=0)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_hide', models.BooleanField(default=0)),
                ('post_approved', models.BooleanField(default=0)),
                ('display_order', models.IntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='base.forum_topics')),
            ],
        ),
    ]
